const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Shirt',
    },
    {
      _id: '2',
      name: 'Addidas Fit Shirt',
      slug: 'addidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Addidas',
      rating: 4.0,
      numReviews: 10,
      description: 'High Quality Shirt',
    },
    {
      _id: '3',
      name: 'Nike Slim Pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'High Quality Pants',
    },
    {
      _id: '4',
      name: 'Addidas Fit Pants',
      slug: 'addidas-fit-pants',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Shirt',
    },
  ],
};
export default data;
